#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <weebo_icons.h>

int32_t weebo_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm weebo!");

    return 0;
}
